version: '3'

services:

  # API
  myapi:
    image: ${DOCKER_REGISTRY-}pocobservability
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - observability-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: Dockerfile


  # PROMETHEUS
  observability.prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observability-network


  # GRAFANA
  observability.grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - observability.prometheus
    networks:
      - observability-network

volumes:
  grafana-storage:

networks:
  observability-network:
    driver: bridge