global:
  scrape_interval: 15s
  scrape_timeout: "10s"

scrape_configs:

  - job_name: 'api'
    static_configs:
      - targets: 
        - api:8080
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
    
  # run docker command to open locally its metrics: dockerd --metrics-addr 0.0.0.0:9323
  - job_name: 'docker-daemon'
    static_configs:
      - targets: ['172.18.16.1:9323']  # Endpoint where docker exposes its metrics routes
  